### ISSUE TITLE
[BUG]Audio Mutes Randomly

### ISSUE THREAD

**Issue by MTsCetin** [ananjaser1211/FloydQ_Reports#123]
Alright. i can safely say the issue is no longer there. (i just hope no random person living in the bahamas manages to trigger the mute again lol) 

with sim + all my social apps pinging multiple times a day. audio is still rock solid.

_Originally posted by @ananjaser1211 in https://github.com/ananjaser1211/FloydQ_Reports/issues/103#issuecomment-640263022_

**Comment by MTsCetin** [comment]
Unfortunately I managed to trigger the bug again, after few phone calls and youtube vanced the phone muted itself...
*I think I am a random person living in the bahamas manages to trigger the mute again*
https://drive.google.com/file/d/1ZnJPm4MYaX7Apzp7bl9iqyvlcR2Fbx77/view?usp=sharing

**Comment by albertodurmiendo** [comment]
Also happening to me sometimes

**Comment by ananjaser1211** [comment]
@MTsCetin When the audio stops working, could you please run this command (in terminal emulator or via adb shell)

`su -c dumpsys media.audio_flinger > /sdcard/dumpsys.log`

(Requires root)

if root is not an option, you can do this, not sure it works on the phone without root, but it works via adb shell fine.

`dumpsys media.audio_flinger > /sdcard/dumpsys.log`

send over the dumpsys log here. would also be great if you can run the same thing, and save a dumpsys with working audio. and once the bug happens, take a new dumpsys with no audio (ofc be sure to change the name of the file so it does not get overwritten)

There are 2 or 3 others that faced this issue, but so far no one really has useful logs. and we are unable to recreate it

**Comment by overlyaddictedgamer** [comment]
Also happened to me. In my case I made a whatsapp call. Since the call was important I didn’t get the time to take a log since I had to quickly restart the phone to get rid of the issue. If it happens again I’ll get the dumpsyS log

**Comment by MetalxD117** [comment]
Could this problem be solved?

**Comment by arkgnan** [comment]
> Also happened to me. In my case I made a whatsapp call. Since the call was important I didn’t get the time to take a log since I had to quickly restart the phone to get rid of the issue. If it happens again I’ll get the dumpsyS log

I get same issue when use whatsapp call, when first call is normal, after second call it is mute the audio. I need to restast the phone to make the audio work again

**Comment by ananjaser1211** [comment]
This makes sense. when the audio is muted, the routing goes to "COMMUNICATION VOICE CALLS" i.e 3rd party calls.

so somewhere in routing, it gets stuck at that stage, and does not route back to normal media playback.

(you can notice that it is stuck in a voice call state by changing the volume while the audio is muted, you should see the ringer slider instead of the media slider)

now that we know the bug for sure, coming up with a fix will be the hard part.

Thanks for the report @arkgnan

**Comment by Rafel17** [comment]
> > Also happened to me. In my case I made a whatsapp call. Since the call was important I didn’t get the time to take a log since I had to quickly restart the phone to get rid of the issue. If it happens again I’ll get the dumpsyS log
> 
> I get same issue when use whatsapp call, when first call is normal, after second call it is mute the audio. I need to restast the phone to make the audio work again

Guys, you don't need to restart at all. If you have magisk root and hKtweaks, simply go to hKtweaks -> sound ->
 tick and untick either Moro Sound Control || or Equalizer

![20200709_150212](https://user-images.githubusercontent.com/68065436/87043549-7c03e600-c1f5-11ea-969f-0e1038954725.jpg)

**Comment by ScorpiionMKD** [comment]
Hope this will help, my phone was idle and didn't have the problem for a few days. When i looked at my phone i had a missed call because of the bug, and i did the root method for log.

https://drive.google.com/folderview?id=1-3LQGx2Hn7bN8YfsmNeQwhI3lWQEwE8p

**Comment by fabiotp91** [comment]
> > > Also happened to me. In my case I made a whatsapp call. Since the call was important I didn’t get the time to take a log since I had to quickly restart the phone to get rid of the issue. If it happens again I’ll get the dumpsyS log
> > 
> > 
> > I get same issue when use whatsapp call, when first call is normal, after second call it is mute the audio. I need to restast the phone to make the audio work again
> 
> Guys, you don't need to restart at all. If you have magisk root and hKtweaks, simply go to hKtweaks -> sound ->
> untick and tick either Moro Sound Control || or Equalizer. Sound is restored immediately after first untick.
> 
> ![20200709_150212](https://user-images.githubusercontent.com/68065436/87043549-7c03e600-c1f5-11ea-969f-0e1038954725.jpg)

This solution does not work for me, I really have to restart the phone to get sound again

**Comment by ananjaser1211** [comment]
So this needs testing. you know how @fabiotp91 mentioned that toggling morosound fixes the mute bug. well a user today reported that he did not face the mute at all for a while, and he had morosound enabled all the time (with different gain set)

so what i am thinking is, can you guys try to keep moro sound and EQ on ALL the time. and see if the mute ever happens.

if this fixes the issue, i can enable both morosound and EQ by default at the kernel level so it works without root. we just need to know if this is responsible for the bug, 

Thanks @M_RavanBakhsh76 for this discovery, i really hope this is it.

**Comment by j1mmyth3k1ng** [comment]
I also tried method with hKtweaks but without any luck, only restart restores the audio.

**Comment by ananjaser1211** [comment]
> I also tried method with hKtweaks but without any luck, only restart restores the audio.

when you enabled hktweaks, did you enable the EQ as well, and then disable Morosound fully. i have not had this bug to test this workaround but that 2 toggles reset the entire audio ic

**Comment by j1mmyth3k1ng** [comment]
> > I also tried method with hKtweaks but without any luck, only restart restores the audio.
> 
> when you enabled hktweaks, did you enable the EQ as well, and then disable Morosound fully. i have not had this bug to test this workaround but that 2 toggles reset the entire audio ic

My settings look like this. Right now I will pay attention to disabling all features of moro and I will reply if it would help.
![Screenshot_20200724-162805_hKtweaks](https://user-images.githubusercontent.com/68728153/88402230-1d309600-cdcb-11ea-8fa7-ecbb9d37d030.jpg)

**Comment by j1mmyth3k1ng** [comment]
So audio mute happened again. I followed your advice but without any luck. Only restart.

**Comment by arkgnan** [comment]
will this issue be fixed in the next version? (V4) without change moro sound toggle (sometimes audio still muted after switch moro sound, I need to restart my phone to unmuted)

**Comment by SypeR54** [comment]
@arkgnan None of the tester had audio muting issues so far. Every sound feature works really good. So we can say, yes its fixed in V4 and will work on final release.

**Comment by ananjaser1211** [comment]
Audio test Patch available Here : https://github.com/ananjaser1211/FloydQ_Reports/issues/176#issuecomment-683873230

It fixes the volume changing in 3rd party calls, and might resolve the muting bug. unsure yet

**Comment by arkgnan** [comment]
> Audio test Patch available Here : [#176 (comment)](https://github.com/ananjaser1211/FloydQ_Reports/issues/176#issuecomment-683873230)
> 
> It fixes the volume changing in 3rd party calls, and might resolve the muting bug. unsure yet

still get audio mute bug after 3 days install the patch. but I only get 1 time, need to change toggle moro sound to make it unmuted

**Comment by phazei** [comment]
I'm on v4 and have installed the patch, still get the mute issue about every other day at least.

The patch did fix an issue where during any video call, after a couple min I get muted and the other person can't hear me untill I hang up and call back.  Though it also introduced an issue where the person I'm talking to gets an echo of whatever they're saying, even if I use ear buds.

**Comment by ierhier** [comment]
Same issue. Tried the test patch, but still same issue. Happens to me when I put my phone in my pocket. If I hold my phone the sounds stays the same volume.

[dumpsys.log](https://github.com/ananjaser1211/FloydQ_Reports/files/5261503/dumpsys.log)

**Comment by Deepak7707** [comment]
Audio issues make this rom unusable.

This is the best rom I saw for s7 edge, but the audio issues (random mute, and others people hear noises during calls and recording) make this rom unusable. Hope that in the next release this issues will be corrected. For now i m changing my rom, but hope to reinstall floyd very soon.

**Comment by ananjaser1211** [comment]
I have marked this now as unconfirmed. While testing V5 (both dirty and clean installations) No testers reported Muting anymore. so this might have been resolved, or our tester base is not large enough (we have ~30 active testers right now)

i will keep this open and wait for reports from you guys when V5 is released. similar to the overnight report

**Comment by Lorenzo-29** [comment]
After few days of testing the V5, I have unfortunately faced the audio mute issue and it seems I'm not the only one. I restarted the phone to get the audio back. I forgot to check if during the issue I was able to make or receive phone call without problem (speaker & mic operational). In V4, even if the ringing was muted, i was able to answer  phone calls. My config: no magisk, no root... Cheers

**Comment by ananjaser1211** [comment]
> After few days of testing the V5, I have unfortunately faced the audio mute issue and it seems I'm not the only one. I restarted the phone to get the audio back. I forgot to check if during the issue I was able to make or receive phone call without problem (speaker & mic operational). In V4, even if the ringing was muted, i was able to answer phone calls. My config: no magisk, no root... Cheers

i need log_all , log_e and log_ril whenever the issue happens. 
what CSC do you use also

**Comment by Lorenzo-29** [comment]
Yep, sorry for that, I'll try to get those logs next time. If I remember, I'm using CSC XEF... French version.

**Comment by roma21515** [comment]
In the last release i too get bug, mute sound after 3 days using, only reboot solve problem

**Comment by mack0r** [comment]
I have this bug very often.  I just installed Logcat (no root).  Is the log from this program useful for identifying the problem?

**Comment by ananjaser1211** [comment]
> I have this bug very often. I just installed Logcat (no root). Is the log from this program useful for identifying the problem?

it would be preferred to use a pc to debug and follow the steps in the main page of this repo. logcat / matlog might cut what we actually need

**Comment by mack0r** [comment]
I would like to help but I do not fully understand.  The mute error occurs once in a while, so how do I save a log of this error.?  If I notice that I have no sound, if I connect the phone to the computer and make a log, will it do anything?  Will it be too late?  Does Logcat have to be started and the phone connected to the computer permanently for the error to be recorded in the logs?

**Comment by JulienMaille** [comment]
Hi @ananjaser1211, as shared on Telegram, I'm able to trigger the bug on a daily basis if I set a custom notification sound. (currently a .wav file, but I believe I had the issue with an ogg on v4)
I managed to get you a Tombstone log file, hope it helps
[tombstone_09.log](https://github.com/ananjaser1211/FloydQ_Reports/files/5649409/tombstone_09.log)

**Comment by bugger23** [comment]
Well as far as i can tell, i'd never faced the audio mute issue. (I'm on V5).Maybe the patch in #176 did fix this issue on V5?

**Comment by Human-OS** [comment]
**May be the error is related to audio driver**
![Screenshot_20210227-134748_Termux](https://user-images.githubusercontent.com/37292720/109384239-a71e7f80-7915-11eb-8c96-9ed0df9ec011.jpg)

**Comment by Human-OS** [comment]
```
[7:HwBinder:3521_1: 3582] lucky-audio sound: lucky_aif_shutdown 
[15379.621454]  [7:HwBinder:3521_1: 3582] lucky-audio sound: codec_dai: moon-aif1
[15379.621460]  [7:HwBinder:3521_1: 3582] lucky-audio sound: playback-eax0-0 playback: 1, capture: 1, active: 2

```

**Comment by Human-OS** [comment]
When the audio is working
```
[ 1573.265390] [2:HwBinder:3520_2: 3586] samsung-lpass 11400000.lpass: power mode: 0x04, dram_used: 0
[ 1573.265504] [2:HwBinder:3520_2: 3586] samsung-lpass 11400000.lpass: LPASS clk status aud_pll = 410000473Hz, aud_lpass = 2
[ 1573.265597] [2:HwBinder:3520_2: 3586] Entered eax_adma_hw_free ++
[ 1573.265653] [2:HwBinder:3520_2: 3586] Entered eax_adma_hw_free --
[ 1573.265716] [2:HwBinder:3520_2: 3586] i2s_shutdown : pri --
[ 1573.265892] [2:HwBinder:3520_2: 3586] i2s_shutdown : pri --
[ 1573.268162] [2:HwBinder:3520_2: 3586] lucky-audio sound: lucky_aif_shutdown
[ 1573.268260] [2:HwBinder:3520_2: 3586] lucky-audio sound: codec_dai: moon-aif1
[ 1573.268331] [2:HwBinder:3520_2: 3586] lucky-audio sound: playback-eax2-0 playback: 0, capture: 1, active: 1
[ 1573.329414] [2:HwBinder:3520_2: 3586] arizona spi0.0: DSP5: Shutdown complete
[ 1573.330186] [2:HwBinder:3520_2: 3586] [MAX98506_DEBUG] max98506_dai_digital_mute: mute=1 playback_active=0 capture_active=0 action=1

```

**Comment by ananjaser1211** [comment]
@Human-OS just saw this, good information, similar to how wifi overnight shutdown was caused by the kernel shutting the wifi dev, this seems like a similar thing

Not much info aside from the I2C driver going nuts, leading to regmap failing. will look more into it soon

**Comment by Human-OS** [comment]
> similar to how wifi overnight shutdown was caused by the kernel shutting the wifi dev, this seems like a similar thing
>Not much info aside from the I2C driver going nuts, leading to regmap failing. will look more into it soon
I connect to wifi through Static IP config and never face wifi overnight shutdown issues.

**Comment by Human-OS** [comment]
### **After Flashing latest MoroKernel All sound issues has been fixed**

[Xda Link off the kernel ](https://forum.xda-developers.com/t/kernel-all-roms-ctk1-morokernel-8-6-1-g93xx-s7-20-12-20.3594754/?__cf_chl_captcha_tk__=8d4726cf6017d4f274c4377a518a05aecbb725ce-1615829461-0-AQ35KZ6rtxthvqYNGMkGQ3KREyTZrxXQm_frv5_PXzcfg1Oyz_PsPxIn3KzTG3rj4mMpqriVExEn_tLQTUobbG36pvLVDj2TjUIa-M_O2o562pSuMSSWxfcU3J6pqWKISXcIadKM-o34efzUvigpkDVDZPJJyiNF-M9UeI1PKAwHFOMsJdsokY7mKDBK_tu_t1gM85KU5658HjPxOKFuaKYHaTNGJjtDYIQxPxOdDU20u1gt1pQI28-bsQKA8cG764r53zhIbN6Wf8fDYd-msfh3mzt4dOIZOSoNm3j-_ELE10h5lOft2h0rIPRvfPaFv0_5qvYTFfmtaTD2ov-f9CEkbsWFkTTHIMgz5nqDnFO26b6oRxUKQMOnVZRjHr08NNzJJcogY396tSxYFM9TKyFJcj8vo1wjKb8w1WgiwaCJepf7FuS0tKZxTUIe0vdy14MrLciBBLtkIT030QtcScH4lImbXtED4fVxPTIqp68cV_To66tm5YEmmC4eh-tai0_gPRg1RPGt67jFdvjOsNGjLyieQ5wEmu70BqZkEZVE_UPuonCY5lMcdy6Atb8vqz5AVFfSjuMkzKkT0cEiUbgRXb9TYJK1FGjZGyQYbyq6k7oq2ZPoD8pJ_Iovmsfi0A)
**Everything sound related looks good in Dmesg **

```

[39774.607796] [4:HwBinder:3597_2: 3669] samsung-lpass 11400000.lpass: power mode: 0x00, dram_used: 0
[39774.607842] [4:HwBinder:3597_2: 3669] samsung-lpass 11400000.lpass: LPASS clk status aud_pll = 410000473Hz, aud_lpass = 2
[39774.607879] [4:HwBinder:3597_2: 3669] Entered eax_adma_hw_free ++
[39774.607897] [4:HwBinder:3597_2: 3669] Entered eax_adma_hw_free --
[39774.607918] [4:HwBinder:3597_2: 3669] i2s_shutdown : pri --
[39774.608038] [4:HwBinder:3597_2: 3669] lpass_put_sync: i2s (use:0)
[39774.608150] [4:HwBinder:3597_2: 3669] i2s_shutdown : pri --
[39774.608173] [4:HwBinder:3597_2: 3669] lucky-audio sound: lucky_aif_shutdown
[39774.608193] [4:HwBinder:3597_2: 3669] lucky-audio sound: codec_dai: moon-aif1
[39774.608214] [4:HwBinder:3597_2: 3669] lucky-audio sound: playback-eax0-0 playback: 0, capture: 0, active: 0
[39774.608311] [4:HwBinder:3597_2: 3669] lucky-audio sound: PMU_DEBUG [0x00000001]
[39774.608332] [4:HwBinder:3597_2: 3669] lucky-audio sound: 26MHz[0], 22.576MHz[0]
[39774.608350] [4:HwBinder:3597_2: 3669] lucky-audio sound: 26MHz[0], 22.576MHz[0]
[39774.608370] [4:HwBinder:3597_2: 3669] lucky-audio sound: lucky_change_mclk: 0 [32768], sysclk_fll(id: 7, out: 49152000)


```

**Comment by ananjaser1211** [comment]
> ### **After Flashing latest MoroKernel All sound issues has been fixed**
> [Xda Link off the kernel ](https://forum.xda-developers.com/t/kernel-all-roms-ctk1-morokernel-8-6-1-g93xx-s7-20-12-20.3594754/?__cf_chl_captcha_tk__=8d4726cf6017d4f274c4377a518a05aecbb725ce-1615829461-0-AQ35KZ6rtxthvqYNGMkGQ3KREyTZrxXQm_frv5_PXzcfg1Oyz_PsPxIn3KzTG3rj4mMpqriVExEn_tLQTUobbG36pvLVDj2TjUIa-M_O2o562pSuMSSWxfcU3J6pqWKISXcIadKM-o34efzUvigpkDVDZPJJyiNF-M9UeI1PKAwHFOMsJdsokY7mKDBK_tu_t1gM85KU5658HjPxOKFuaKYHaTNGJjtDYIQxPxOdDU20u1gt1pQI28-bsQKA8cG764r53zhIbN6Wf8fDYd-msfh3mzt4dOIZOSoNm3j-_ELE10h5lOft2h0rIPRvfPaFv0_5qvYTFfmtaTD2ov-f9CEkbsWFkTTHIMgz5nqDnFO26b6oRxUKQMOnVZRjHr08NNzJJcogY396tSxYFM9TKyFJcj8vo1wjKb8w1WgiwaCJepf7FuS0tKZxTUIe0vdy14MrLciBBLtkIT030QtcScH4lImbXtED4fVxPTIqp68cV_To66tm5YEmmC4eh-tai0_gPRg1RPGt67jFdvjOsNGjLyieQ5wEmu70BqZkEZVE_UPuonCY5lMcdy6Atb8vqz5AVFfSjuMkzKkT0cEiUbgRXb9TYJK1FGjZGyQYbyq6k7oq2ZPoD8pJ_Iovmsfi0A)
> [Latest morokernel with magisk22 patch in xda post](https://forum.xda-developers.com/t/rom-10-0-oneui-2-5-g930x-g935x-n930x-n935x-floydq-v5-0.4085667/post-84663177)
> 
> **Everything sound related looks good in Dmesg **
> 
> ```
> 
> [39774.607796] [4:HwBinder:3597_2: 3669] samsung-lpass 11400000.lpass: power mode: 0x00, dram_used: 0
> [39774.607842] [4:HwBinder:3597_2: 3669] samsung-lpass 11400000.lpass: LPASS clk status aud_pll = 410000473Hz, aud_lpass = 2
> [39774.607879] [4:HwBinder:3597_2: 3669] Entered eax_adma_hw_free ++
> [39774.607897] [4:HwBinder:3597_2: 3669] Entered eax_adma_hw_free --
> [39774.607918] [4:HwBinder:3597_2: 3669] i2s_shutdown : pri --
> [39774.608038] [4:HwBinder:3597_2: 3669] lpass_put_sync: i2s (use:0)
> [39774.608150] [4:HwBinder:3597_2: 3669] i2s_shutdown : pri --
> [39774.608173] [4:HwBinder:3597_2: 3669] lucky-audio sound: lucky_aif_shutdown
> [39774.608193] [4:HwBinder:3597_2: 3669] lucky-audio sound: codec_dai: moon-aif1
> [39774.608214] [4:HwBinder:3597_2: 3669] lucky-audio sound: playback-eax0-0 playback: 0, capture: 0, active: 0
> [39774.608311] [4:HwBinder:3597_2: 3669] lucky-audio sound: PMU_DEBUG [0x00000001]
> [39774.608332] [4:HwBinder:3597_2: 3669] lucky-audio sound: 26MHz[0], 22.576MHz[0]
> [39774.608350] [4:HwBinder:3597_2: 3669] lucky-audio sound: 26MHz[0], 22.576MHz[0]
> [39774.608370] [4:HwBinder:3597_2: 3669] lucky-audio sound: lucky_change_mclk: 0 [32768], sysclk_fll(id: 7, out: 49152000)
> [39751.311817] [6:HwBinder:3597_2: 3669] arizona spi0.0: DSP5: Shutdown complete
> [39751.312799] [6:HwBinder:3597_2: 3669] [MAX98506_DEBUG] max98506_dai_digital_mute: mute=1 playback_active=0 capture_active=0 action=1
> [39751.337649] [5:HwBinder:3597_2: 3669] [MAXIM_DSM] maxdsm_log_update: [MAX|OVCNT] EX [0|0] TEMP [0|0]
> [39751.360481] [5:HwBinder:3597_2: 3669] [MAXIM_DSM] maxdsm_log_update: [MAX|OVCNT] EX [0|0] TEMP [0|0]
> ```

we tested moro v8.6.1, it had the mute issue, we use pretty much the same upstream base / drivers so it is to be expected, when the issue was triggered, it showed similar dmsg to what you sent with the H2IC error, the issue seems to be that the driver is sleeping and not waking up, we were testing few IRQ changes by pascau (elite kernel dev) , it did help but it does not fix the issue fully yet as far as i know,

the issue is random, but the best way to trigger is is through setting custom notification sound as @JulienMaille found, so far that triggered the issue on any fix i have tried the past month or so.

i am a bit AFK from the scene for now, i will look more into this issue when i am back.

**Comment by Human-OS** [comment]
> we tested moro v8.6.1, it had the mute issue, we use pretty much the same upstream base / drivers so it is to be expected, when the issue was triggered, it showed similar dmsg to what you sent with the H2IC error, the issue seems to be that the driver is sleeping and not waking up, we were testing few IRQ changes by pascau (elite kernel dev) , it did help but it does not fix the issue fully yet as far as i know,
> 
> the issue is random, but the best way to trigger is is through setting custom notification sound as @JulienMaille found, so far that triggered the issue on any fix i have tried the past month or so.
> 
it is notable that after flashing the kernel, **i also underclocked it**. Before I also changed the system sound mod to retro. still now, i don't face the audio issues.

**Comment by ananjaser1211** [comment]
if for any reason you get audio mute in v6, open a new issue, but i will most likely mark it as a one off bug, as only 2 people can recreate this issue sometimes. rest no longer have it.
